### Model Metrics

#### Regression Metrics

In [6]:
# RMSE, R_2 and MAE

#### Classification Metrics

In [ ]:
# Accuracy, Precision, and Recall
# THIS Metrics Calculated Based on TP, TN, FP, FN
# print(classification_report(y_pred, y_test)) from sklearn.metrics

#### Clustering Metrics

In [3]:
# https://www.geeksforgeeks.org/machine-learning/clustering-metrics/

#### Coefficient of determination: R Squared

$$
R^2 = 1 - \frac{\sum (y_{real} - y_{pred})^2}{\sum (y_{real} - \bar{y})^2}
$$

The coefficient of determination (R²) is a metric used in regression to measure how well the model explains the data or how data fit model. \ 
- first sum is the sequare error
- second sum is varaince
- fraction is percentage of data that can not explain it by the model
- we add 1 - fraction: to get percentage of data that can explain it.

**Values that accept:**
- (R^2 = 1) → perfect prediction  
- (R^2 = 0) → model explains nothing
- (R^2 = 0.8) → model explain 80% of data
  
**Problems:**
- adding more features in model can ne nothing happen or explain MORE --> this is bad
- does not really tell us our model Goor or Bas
  - model have hight R2 but still large residuals
- R2 is good for linear models (not so much random forset --> OOB, neural networks, ...)
---

#### Ajusted R Squared

R2 = 1 - ((1 - R2) * (n - 1) / (n - p - 1)) \
where:
- R² = r-squared of the model
- n = number of observations (data points)
- p = number of predictors (independent variables)

R-2 measures how well a regression model explains the data. It always stays the same or goes up when \
you add more variables, even if they don’t really help.

Adjusted R-squared fixes this by penalizing extra variables that don’t improve the model. It can go down \
if a new predictor doesn’t help, so it’s more reliable for deciding which variables to keep.

#### Mean Absolute Error (MAE)

Mean Absolute Error (MAE) is a statistical measure that evaluates the accuracy of a predictive model by calculating the average of the absolute differences between predicted and actual values.

**Formula:**

$$
MAE = \frac{1}{n} \sum |y_{real} - y_{pred}|
$$

- the best mae is zero
---

#### Root Mean Squared Error (RMSE)

Root Mean Squared Error (RMSE) measures the average difference between a model’s predicted values and the actual values.

**Formula:**

$$
RMSE = \sqrt{\frac{1}{n} \sum (y_{real} - y_{pred})^2}
$$

---

**Source:** https://statisticsbyjim.com/regression/root-mean-square-error-rmse/

### Data Normalisation and Standardization

Normalization is a step in data preprocessing used when preparing data for building a model.  
It consists of making all feature values between 0 and 1.  

Some Benefits
- Hard to compare features with different scales  
- Big values can influence the result  
- Improves model performance and stability  

How to Normalize Our Data (Techniques)

- Simple Feature Scaling: Divide each value by the maximum value: \
**Formula:**  x' = x / x_max

- Min-Max Scaling: Scale each value between 0 and 1 using min and max: \
**Formula:**  x' = (x - x_min) / (x_max - x_min)

- Z-Score (Standardization): Center data around mean with standard deviation: \
**Formula:**  x' = (x - μ) / σ

    - μ = average of the feature  
    - σ = standard deviation of the feature  

- NOTE: in Random Forset We Do not ned normalisation

Source: https://www.youtube.com/watch?v=uvqkZf3zKQo

In [4]:
import pandas as pd

In [24]:
data = pd.read_csv("./dataset/Games.csv")
data = data.drop("Unnamed: 0", axis=1)
data.head(2)

        Genre  Production_cost  profit
0  Asset Flip              100    1000
1  Text Based              500    3000

In [30]:
# Normalise The Data (Feature Product_cost and Profit)
# simple feature Scaling:
data["profit"] = data["profit"] / (data["profit"].max())
data.head(3)

# Min-Max:
data["Production_cost"] = (data["Production_cost"] - data["Production_cost"].min()) / (data["Production_cost"].max() - data["Production_cost"].min())
data.head(3)

# Zero-Score:
data["profit"] = (data["profit"] - data["profit"].mean()) - (data["profit"].std())

### Encoding Features

some times in building model we find some feature very important and it can inhance our accurary prediction but it look as string. \
and in this case we need Encoding means make teh values from string to numbers.\
this features can be categorical varaible OR ... \
and it is one of **preprocessing step**

how it works:
- for each feature value it give him a number generated

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
# iMport Data
data = pd.read_csv("./dataset/Games.csv")
le = LabelEncoder()

# Encode The Genre Feature
data["Genre"] = le.fit_transform(y=data["Genre"])
data.head(2)

   Unnamed: 0  Genre  Production_cost  profit
0           0      2              100    1000
1           1     12              500    3000

### One Encoding Vs Label Encoding

- One-Hot Encoding converts each category of a categorical variable into a new binary column
  - best for nominal varaibles like (colors, countries, ...)
  - this Increase dimensionality of the dataset
  - high memory usage
- Label Encoding convert we have ordinal data varaibles that have order (Low, Meduim, High, ...)
  - create a single column keeping same feature number

### Correlation

- Formula
r = Σ((Xi - Mean(X)) * (Yi - Mean(Y)))  /  √(Σ(Xi - Mean(X))² * Σ(Yi - Mean(Y))²)
- Definition
Correlation is a statistical concept that measures the relation between two variables.
- Types of Correlation
  - Positive Correlation: both variables increase or decrease together  
  - Zero Correlation: no linear relation between two variables  
  - Negative Correlation: one variable increases while the other decreases  
- Range: It ranges from -1 to 1  
- Note: Covariance detects only the direction of two variables

### Varaince and Standard Deviation

- Definition
It is used to measure how data spread out from the average.

- Variance
It shows if data vary from the average (are values far from the mean or not).

- Standard Deviation
It is the square root of the variance.
It is used to express the variance in the same unit as the data (DH, KG, ...).

### Covraince (X, Y)

- Definition
It is used to see if two variables move together or not, or to measure the linear relationship.

- Cases
  - cov(x, y) > 0: when X increases, Y also increases
  - cov(x, y) < 0: when X increases, Y decreases
  - cov(x, y) = 0: no relation between variables

- Range
Covariance can take any value from -inf to +inf

- Note
It gives only the direction of the relationship between two variables

### Distrubution For a Varaible

A distribution in statistics is a function that shows the possible values for a variable and how often they occur.